import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from 'components/header'
import { FeaturedProduct } from 'types/type';

type HomeProps = {
  featuredProduct: FeaturedProduct;
}

const Home: NextPage<HomeProps> = ({
  featuredProduct
}) => {
  return (
    <>
      <Header />
      <div className="pt-[124px] sm:pt-[186px]">
        <Head>
          <title>Bejamas - task</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </>
  )
}

export default Home

export const getStaticProps = async () => {

  const featuredProduct = await fetch(`${process.env.API_URL}/featured-product`)
  return {
    props: {
      featuredProduct: await featuredProduct.json() 
    }
  }
}